[package]
name = "ex3-1"
version = "0.1.0"
authors = ["pettan0818 <pettan0818+git@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
