[package]
name = "sol3-1"
version = "0.1.0"
authors = ["pettan0818 <pettan0818+git@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.1"
itertools = "0.10.0"
permutator = "0.4.0"